server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost/vue_board?serverTimezone=UTC&useSSL=false
    username: root
    password: 5959@Ssol
    driverClassName: com.mysql.cj.jdbc.Driver