server:
    port: 8888

spring:
    datasource:
        url: jdbc:mysql://localhost/personalproject?serverTimezone=UTC&useSSL=false
        username: root
        password: dkdlxl123
        driver-class-name: com.mysql.cj.jdbc.Driver
