server:
  port: 8888
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/personalproject?serverTimezone=UTC&useSSL=false
    username: root
    password: dkdlxl123
    driverClassName: com.mysql.cj.jdbc.Driver