server:
    port: 8888

spring:
    datasource:
        url: jdbc:mysql://localhost/board_test?serverTimeZone=UTC&useSSl=false
        username: root
        password: dkdlxl123
        driver-class-name: com.mysql.cj.jdbc.Driver
