server:
    port: 7777

spring:
    datasource:
        url: jdbc:mysql://localhost/board_test?serverTimezone=UTC&useSSL=false
        username: seulgi
        password: dkdlxl123
        driverClassName: com.mysql.cj.jdbc.Driver
