server:
  port: 7799

spring:
  datasource:
    url: jdbc:mysql://localhost/board_test?serverTimezone=UTC&useSSL=false
    username: bitweb
    password: dkdlxl123
    driverClassName: com.mysql.cj.jdbc.Driver