/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_nativeinterface_HelloSpring */

#ifndef _Included_com_example_demo_nativeinterface_HelloSpring
#define _Included_com_example_demo_nativeinterface_HelloSpring
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_nativeinterface_HelloSpring
 * Method:    print
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_demo_nativeinterface_HelloSpring_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
